# Generated by Django 3.2.5 on 2021-07-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Centers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=30)),
                ('Center_name', models.CharField(max_length=30)),
                ('Center_id', models.IntegerField()),
            ],
        ),
    ]
