# Generated by Django 3.2.5 on 2021-07-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='centers',
            name='y',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
