# Generated by Django 3.2.5 on 2021-07-27 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_centers_y'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=30)),
                ('OTP', models.IntegerField()),
                ('Time', models.TimeField()),
            ],
        ),
    ]
